package moodleassignment_2;
import java.util.*;

public class countryCode {
    public static void main(String[] args) {
        
        Map<String, List<String>> countryNeighbors = new HashMap<>();

        // Adding all countries and their neighbors
        countryNeighbors.put("AF", Arrays.asList("Iran", "Pakistan", "Turkmenistan", "Uzbekistan", "Tajikistan", "China"));
        countryNeighbors.put("AL", Arrays.asList("Montenegro", "Serbia", "North Macedonia", "Greece"));
        countryNeighbors.put("DZ", Arrays.asList("Tunisia", "Libya", "Niger", "Mali", "Mauritania", "Western Sahara", "Morocco"));
        countryNeighbors.put("AD", Arrays.asList("Spain", "France"));
        countryNeighbors.put("AO", Arrays.asList("Democratic Republic of the Congo", "Zambia", "Namibia"));
        countryNeighbors.put("AG", Collections.emptyList()); 
        countryNeighbors.put("AR", Arrays.asList("Chile", "Bolivia", "Paraguay", "Brazil", "Uruguay"));
        countryNeighbors.put("AM", Arrays.asList("Georgia", "Azerbaijan", "Iran", "Turkey"));
        countryNeighbors.put("AU", Collections.emptyList()); 
        countryNeighbors.put("AT", Arrays.asList("Germany", "Czechia", "Slovakia", "Hungary", "Slovenia", "Italy", "Switzerland", "Liechtenstein"));
        countryNeighbors.put("AZ", Arrays.asList("Russia", "Georgia", "Armenia", "Iran"));
        countryNeighbors.put("BS", Collections.emptyList()); 
        countryNeighbors.put("BH", Collections.emptyList()); 
        countryNeighbors.put("BD", Arrays.asList("India", "Myanmar"));
        countryNeighbors.put("BB", Collections.emptyList()); 
        countryNeighbors.put("BY", Arrays.asList("Latvia", "Lithuania", "Poland", "Russia", "Ukraine"));
        countryNeighbors.put("BE", Arrays.asList("France", "Germany", "Luxembourg", "Netherlands"));
        countryNeighbors.put("BZ", Arrays.asList("Mexico", "Guatemala"));
        countryNeighbors.put("BJ", Arrays.asList("Togo", "Nigeria", "Burkina Faso", "Niger"));
        countryNeighbors.put("BT", Arrays.asList("India", "China"));
        countryNeighbors.put("BO", Arrays.asList("Peru", "Brazil", "Paraguay", "Argentina", "Chile"));
        countryNeighbors.put("BA", Arrays.asList("Croatia", "Montenegro", "Serbia"));
        countryNeighbors.put("BW", Arrays.asList("Namibia", "South Africa", "Zimbabwe", "Zambia"));
        countryNeighbors.put("BR", Arrays.asList("Argentina", "Bolivia", "Colombia", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay", "Venezuela", "French Guiana"));
        countryNeighbors.put("BN", Arrays.asList("Malaysia"));
        countryNeighbors.put("BG", Arrays.asList("Greece", "North Macedonia", "Romania", "Serbia", "Turkey"));
        countryNeighbors.put("BF", Arrays.asList("Mali", "Niger", "Benin", "Togo", "Ghana", "Ivory Coast"));
        countryNeighbors.put("BI", Arrays.asList("Rwanda", "Tanzania", "Democratic Republic of the Congo"));
        countryNeighbors.put("KH", Arrays.asList("Thailand", "Vietnam", "Laos"));
        countryNeighbors.put("CM", Arrays.asList("Nigeria", "Chad", "Central African Republic", "Equatorial Guinea", "Gabon", "Republic of the Congo"));
        countryNeighbors.put("CA", Arrays.asList("United States"));
        countryNeighbors.put("CV", Collections.emptyList()); 
        countryNeighbors.put("CF", Arrays.asList("Cameroon", "Chad", "Democratic Republic of the Congo", "Republic of the Congo", "South Sudan", "Sudan"));
        countryNeighbors.put("TD", Arrays.asList("Libya", "Sudan", "Central African Republic", "Cameroon", "Nigeria", "Niger"));
        countryNeighbors.put("CL", Arrays.asList("Peru", "Bolivia", "Argentina"));
        countryNeighbors.put("CN", Arrays.asList("Afghanistan", "Bhutan", "India", "Kazakhstan", "Kyrgyzstan", "Laos", "Mongolia", "Myanmar", "Nepal", "North Korea", "Pakistan", "Russia", "Tajikistan", "Vietnam"));
        countryNeighbors.put("CO", Arrays.asList("Panama", "Venezuela", "Brazil", "Peru", "Ecuador"));
        countryNeighbors.put("KM", Collections.emptyList()); 
        countryNeighbors.put("CG", Arrays.asList("Angola", "Central African Republic", "Democratic Republic of the Congo", "Gabon"));
        countryNeighbors.put("CD", Arrays.asList("Angola", "Burundi", "Central African Republic", "Republic of the Congo", "Rwanda", "South Sudan", "Tanzania", "Uganda", "Zambia"));
        countryNeighbors.put("CR", Arrays.asList("Nicaragua", "Panama"));
        countryNeighbors.put("CI", Arrays.asList("Ghana", "Liberia", "Burkina Faso", "Mali", "Guinea"));
        countryNeighbors.put("HR", Arrays.asList("Bosnia and Herzegovina", "Hungary", "Montenegro", "Serbia", "Slovenia"));
        countryNeighbors.put("CU", Collections.emptyList()); 
        countryNeighbors.put("CY", Arrays.asList("Turkey")); 
        countryNeighbors.put("CZ", Arrays.asList("Austria", "Germany", "Poland", "Slovakia"));
        countryNeighbors.put("DK", Arrays.asList("Germany"));
        countryNeighbors.put("DJ", Arrays.asList("Eritrea", "Ethiopia", "Somalia"));
        countryNeighbors.put("DO", Arrays.asList("Haiti"));
        countryNeighbors.put("EG", Arrays.asList("Libya", "Sudan", "Israel"));
        countryNeighbors.put("SV", Arrays.asList("Guatemala", "Honduras"));
        countryNeighbors.put("EE", Arrays.asList("Latvia", "Russia"));
        countryNeighbors.put("ET", Arrays.asList("Eritrea", "Djibouti", "Somalia", "Kenya", "South Sudan", "Sudan"));
        countryNeighbors.put("FJ", Collections.emptyList());
        countryNeighbors.put("FI", Arrays.asList("Norway", "Sweden", "Russia"));
        countryNeighbors.put("FR", Arrays.asList("Belgium", "Luxembourg", "Germany", "Switzerland", "Italy", "Monaco", "Spain"));
        countryNeighbors.put("GA", Arrays.asList("Equatorial Guinea", "Gabon", "Cameroon"));
        countryNeighbors.put("GM", Arrays.asList("Senegal"));
        countryNeighbors.put("GE", Arrays.asList("Russia", "Turkey", "Armenia", "Azerbaijan"));
        countryNeighbors.put("DE", Arrays.asList("Denmark", "Poland", "Czechia", "Austria", "Switzerland", "France", "Luxembourg", "Belgium"));
        countryNeighbors.put("GH", Arrays.asList("Burkina Faso", "Togo", "Ivory Coast"));
        countryNeighbors.put("GR", Arrays.asList("Albania", "North Macedonia", "Bulgaria", "Turkey"));
        countryNeighbors.put("GD", Collections.emptyList()); 
        countryNeighbors.put("GT", Arrays.asList("Mexico", "Belize", "Honduras"));
        countryNeighbors.put("GN", Arrays.asList("Guinea-Bissau", "Liberia", "Ivory Coast", "Mali", "Senegal"));
        countryNeighbors.put("GW", Arrays.asList("Guinea", "Senegal"));
        countryNeighbors.put("GY", Arrays.asList("Venezuela", "Brazil", "Suriname"));
        countryNeighbors.put("HT", Arrays.asList("Dominican Republic"));
        countryNeighbors.put("HN", Arrays.asList("Guatemala", "El Salvador", "Nicaragua"));
        countryNeighbors.put("HU", Arrays.asList("Austria", "Slovakia", "Ukraine", "Romania", "Serbia", "Croatia", "Slovenia"));
        countryNeighbors.put("IS", Collections.emptyList()); 
        countryNeighbors.put("IN", Arrays.asList("China", "Pakistan", "Nepal", "Bhutan", "Bangladesh", "Myanmar"));
        countryNeighbors.put("ID", Arrays.asList("Malaysia", "Papua New Guinea"));
        countryNeighbors.put("IR", Arrays.asList("Armenia", "Azerbaijan", "Turkey", "Iraq", "Pakistan", "Afghanistan", "Turkmenistan"));
        countryNeighbors.put("IQ", Arrays.asList("Turkey", "Iran", "Kuwait", "Saudi Arabia", "Jordan", "Syria"));
        countryNeighbors.put("IE", Arrays.asList("United Kingdom"));
        countryNeighbors.put("IL", Arrays.asList("Lebanon", "Syria", "Jordan", "Egypt"));
        countryNeighbors.put("IT", Arrays.asList("France", "Switzerland", "Austria", "Slovenia"));
        countryNeighbors.put("JM", Collections.emptyList()); 
        countryNeighbors.put("JP", Arrays.asList("Russia")); 
        countryNeighbors.put("JO", Arrays.asList("Syria", "Iraq", "Saudi Arabia", "Israel", "Palestinian Territories"));
        countryNeighbors.put("KZ", Arrays.asList("Russia", "China", "Kyrgyzstan", "Uzbekistan", "Turkmenistan"));
        countryNeighbors.put("KE", Arrays.asList("Ethiopia", "Somalia", "Uganda", "Tanzania"));
        countryNeighbors.put("KI", Collections.emptyList()); // Island nation
        countryNeighbors.put("KR", Arrays.asList("North Korea"));
        countryNeighbors.put("KW", Arrays.asList("Iraq", "Saudi Arabia"));
        countryNeighbors.put("KG", Arrays.asList("Kazakhstan", "Uzbekistan", "Tajikistan", "Kyrgyzstan"));
        countryNeighbors.put("LA", Arrays.asList("China", "Vietnam", "Thailand", "Myanmar"));
        countryNeighbors.put("LV", Arrays.asList("Estonia", "Russia", "Lithuania"));
        countryNeighbors.put("LB", Arrays.asList("Syria", "Israel"));
        countryNeighbors.put("LS", Arrays.asList("South Africa"));
        countryNeighbors.put("LR", Arrays.asList("Guinea", "Ivory Coast"));
        countryNeighbors.put("LY", Arrays.asList("Algeria", "Chad", "Egypt", "Niger", "Sudan", "Tunisia"));
        countryNeighbors.put("LI", Arrays.asList("Switzerland", "Austria"));
        countryNeighbors.put("LT", Arrays.asList("Latvia", "Poland", "Belarus"));
        countryNeighbors.put("LU", Arrays.asList("Belgium", "France", "Germany"));
        countryNeighbors.put("MG", Arrays.asList("Mozambique"));
        countryNeighbors.put("MW", Arrays.asList("Tanzania", "Zambia", "Mozambique", "Malawi"));
        countryNeighbors.put("MY", Arrays.asList("Thailand", "Singapore", "Brunei", "Indonesia"));
        countryNeighbors.put("MV", Collections.emptyList()); 
        countryNeighbors.put("ML", Arrays.asList("Algeria", "Niger", "Burkina Faso", "Cote d'Ivoire", "Guinea", "Senegal", "Mauritania"));
        countryNeighbors.put("MT", Collections.emptyList()); 
        countryNeighbors.put("MH", Arrays.asList("United States", "Guam", "Northern Mariana Islands"));
        countryNeighbors.put("MR", Arrays.asList("Western Sahara", "Algeria", "Mali"));
        countryNeighbors.put("MU", Arrays.asList("Reunion"));
        countryNeighbors.put("MX", Arrays.asList("United States", "Guatemala", "Belize"));
        countryNeighbors.put("FM", Arrays.asList("Guam", "Palau", "Marshall Islands"));
        countryNeighbors.put("MD", Arrays.asList("Ukraine", "Romania"));
        countryNeighbors.put("MC", Collections.emptyList()); 
        countryNeighbors.put("MN", Arrays.asList("Russia", "China"));
        countryNeighbors.put("ME", Arrays.asList("Croatia", "Bosnia and Herzegovina", "Serbia"));
        countryNeighbors.put("MA", Arrays.asList("Algeria", "Western Sahara", "Mauritania"));
        countryNeighbors.put("MZ", Arrays.asList("Tanzania", "Zambia", "Malawi", "South Africa", "Swaziland", "Zimbabwe"));
        countryNeighbors.put("MM", Arrays.asList("China", "India", "Bangladesh", "Laos", "Thailand"));
        countryNeighbors.put("NA", Arrays.asList("Angola", "Zambia"));
        countryNeighbors.put("NR", Collections.emptyList()); 
        countryNeighbors.put("NP", Arrays.asList("India", "China"));
        countryNeighbors.put("NL", Arrays.asList("Belgium", "Germany"));
        countryNeighbors.put("NZ", Collections.emptyList()); 
        countryNeighbors.put("NI", Arrays.asList("Honduras", "Costa Rica"));
        countryNeighbors.put("NE", Arrays.asList("Mali", "Burkina Faso", "Benin", "Nigeria"));
        countryNeighbors.put("NG", Arrays.asList("Benin", "Chad", "Niger", "Cameroon"));
        countryNeighbors.put("NO", Arrays.asList("Sweden", "Finland", "Russia"));
        countryNeighbors.put("OM", Arrays.asList("Yemen", "Saudi Arabia", "UAE"));
        countryNeighbors.put("PK", Arrays.asList("India", "Afghanistan", "Iran", "China"));
        countryNeighbors.put("PW", Arrays.asList("United States"));
        countryNeighbors.put("PS", Arrays.asList("Israel", "Jordan"));
        countryNeighbors.put("PA", Arrays.asList("Costa Rica", "Colombia"));
        countryNeighbors.put("PG", Arrays.asList("Indonesia"));
        countryNeighbors.put("PY", Arrays.asList("Argentina", "Brazil", "Bolivia"));
        countryNeighbors.put("PE", Arrays.asList("Ecuador", "Colombia", "Brazil", "Bolivia", "Chile"));
        countryNeighbors.put("PH", Collections.emptyList()); 
        countryNeighbors.put("PL", Arrays.asList("Germany", "Czechia", "Slovakia", "Ukraine", "Belarus", "Lithuania"));
        countryNeighbors.put("PT", Arrays.asList("Spain"));
        countryNeighbors.put("QA", Arrays.asList("Saudi Arabia"));
        countryNeighbors.put("RO", Arrays.asList("Ukraine", "Moldova", "Bulgaria", "Serbia", "Hungary"));
        countryNeighbors.put("RU", Arrays.asList("Norway", "Finland", "Estonia", "Latvia", "Lithuania", "Poland", "Belarus", "Ukraine", "Georgia", "Azerbaijan", "Kazakhstan", "China", "Mongolia", "North Korea"));
        countryNeighbors.put("RW", Arrays.asList("Uganda", "Tanzania", "Burundi", "Democratic Republic of the Congo"));
        countryNeighbors.put("KN", Collections.emptyList()); 
        countryNeighbors.put("LC", Collections.emptyList()); 
        countryNeighbors.put("SM", Collections.emptyList());
        countryNeighbors.put("ST", Collections.emptyList()); 
        countryNeighbors.put("SA", Arrays.asList("Jordan", "Iraq", "Kuwait", "Bahrain", "Qatar", "UAE", "Oman", "Yemen"));
        countryNeighbors.put("SN", Arrays.asList("Mauritania", "Mali", "Guinea", "Guinea-Bissau", "Gambia", "Ivory Coast"));
        countryNeighbors.put("RS", Arrays.asList("Hungary", "Romania", "Bulgaria", "Macedonia", "Albania", "Montenegro", "Bosnia and Herzegovina", "Croatia"));
        countryNeighbors.put("SC", Collections.emptyList());
        countryNeighbors.put("SL", Arrays.asList("Guinea", "Liberia"));
        countryNeighbors.put("SG", Arrays.asList("Malaysia"));
        countryNeighbors.put("SK", Arrays.asList("Czechia", "Austria", "Poland", "Ukraine", "Hungary"));
        countryNeighbors.put("SI", Arrays.asList("Austria", "Italy", "Croatia"));
        countryNeighbors.put("SO", Arrays.asList("Ethiopia", "Djibouti", "Kenya"));
        countryNeighbors.put("ZA", Arrays.asList("Namibia", "Botswana", "Zimbabwe", "Mozambique", "Eswatini", "Lesotho"));
        countryNeighbors.put("SS", Arrays.asList("Sudan", "Ethiopia", "Kenya", "Uganda", "Democratic Republic of the Congo", "Central African Republic", "Sudan"));
        countryNeighbors.put("ES", Arrays.asList("France", "Portugal"));
        countryNeighbors.put("LK", Arrays.asList("India"));
        countryNeighbors.put("SD", Arrays.asList("Egypt", "Eritrea", "Ethiopia", "South Sudan", "Chad", "Libya"));
        countryNeighbors.put("SR", Arrays.asList("French Guiana", "Brazil", "Guyana"));
        countryNeighbors.put("SE", Arrays.asList("Norway", "Finland"));
        countryNeighbors.put("SY", Arrays.asList("Turkey", "Iraq", "Jordan", "Lebanon", "Israel"));
        countryNeighbors.put("TJ", Arrays.asList("Kyrgyzstan", "Uzbekistan", "Afghanistan", "China"));
        countryNeighbors.put("TH", Arrays.asList("Myanmar", "Laos", "Cambodia", "Vietnam", "Malaysia"));
        countryNeighbors.put("TM", Arrays.asList("Kazakhstan", "Uzbekistan", "Afghanistan", "Iran"));
        countryNeighbors.put("TL", Arrays.asList("Indonesia"));
        countryNeighbors.put("TO", Collections.emptyList());
        countryNeighbors.put("TR", Arrays.asList("Greece", "Bulgaria", "Georgia", "Armenia", "Azerbaijan", "Iran", "Iraq", "Syria"));
        countryNeighbors.put("TT", Collections.emptyList());
        countryNeighbors.put("TN", Arrays.asList("Algeria", "Libya"));
        countryNeighbors.put("TM", Arrays.asList("Kazakhstan", "Uzbekistan", "Afghanistan", "Iran"));
        countryNeighbors.put("UG", Arrays.asList("South Sudan", "Kenya", "Tanzania", "Rwanda", "Democratic Republic of the Congo"));
        countryNeighbors.put("UA", Arrays.asList("Russia", "Belarus", "Poland", "Slovakia", "Hungary", "Romania", "Moldova"));
        countryNeighbors.put("AE", Arrays.asList("Saudi Arabia", "Oman"));
        countryNeighbors.put("GB", Arrays.asList("Ireland"));
        countryNeighbors.put("US", Arrays.asList("Canada", "Mexico"));
        countryNeighbors.put("UY", Arrays.asList("Argentina", "Brazil"));
        countryNeighbors.put("UZ", Arrays.asList("Kazakhstan", "Kyrgyzstan", "Tajikistan", "Afghanistan", "Turkmenistan"));
        countryNeighbors.put("VE", Arrays.asList("Colombia", "Brazil", "Guyana", "Suriname"));
        countryNeighbors.put("VN", Arrays.asList("China", "Laos", "Cambodia"));
        countryNeighbors.put("YE", Arrays.asList("Saudi Arabia", "Oman"));
        countryNeighbors.put("ZM", Arrays.asList("Tanzania", "Malawi", "Mozambique", "Zimbabwe", "Botswana", "Namibia"));
        countryNeighbors.put("ZW", Arrays.asList("Zambia", "Mozambique", "South Africa", "Botswana"));

        Scanner scanner = new Scanner(System.in);

        System.out.println("Enter the country code (e.g., US, FR, AL): ");
        String countryCode = scanner.nextLine().toUpperCase();

        // Find and display the neighbors
        if (countryNeighbors.containsKey(countryCode)) {
            List<String> neighbors = countryNeighbors.get(countryCode);
            if (neighbors.isEmpty()) {
                System.out.println("The country has no neighboring countries.");
            } else {
                System.out.println("Neighboring countries of " + countryCode + ": " + neighbors);
            }
        } else {
            System.out.println("Country code not found. Please check and try again.");
        }

        scanner.close();
    }
